# Generated by Django 3.1.1 on 2020-09-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpApp', '0002_projectdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdata',
            name='upload',
            field=models.FileField(upload_to=''),
        ),
    ]
