# Generated by Django 3.1.1 on 2020-09-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpApp', '0003_auto_20200929_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdata',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
