# Generated by Django 3.1.1 on 2020-09-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpApp', '0006_auto_20200930_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('projectName', models.CharField(max_length=100)),
                ('projectPercenatge', models.CharField(max_length=100)),
                ('upload', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='registerdata',
            name='projectName',
        ),
        migrations.RemoveField(
            model_name='registerdata',
            name='projectPercenatge',
        ),
        migrations.RemoveField(
            model_name='registerdata',
            name='upload',
        ),
    ]
