# Generated by Django 3.1.1 on 2020-10-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpApp', '0008_admindata'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdata',
            name='url',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
